---
title: |
  | \LARGE Homework #5
author: |
  | \large \rm 2019150432 임효진
date: |
  | \rm \today
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
mainfont: NanumBarunGothic
fontsize: 11pt
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "center",
	fig.height = 4,
	fig.width = 5,
	message = FALSE,
	warning = FALSE,
	out.width = "50%"
)
library(tidyverse)
library(stringr)
```

# 2
## (a)
### (1)
```{r}
#"\" doesn't esape the backslash.
#"\\" means "\" but needs 2 \\ to escape.
#"\\\" needs another \ to escape.
```

### (2)
```{r}
#"\"'\\\\"
```

### (3)
```{r}
#It will match string such as .a.a.a 
#It could be represented as a string by "\\..\\..\\..".
```

## (b)
### (1)
"^[aeiou]"
"[^aeiou]"
"[^e]ed$"
"i(ng|se)$"

### (2)
One can use str_detect with regex "(^ie)|[^c]ie".

### (3)
One can use str_detect with regex "q[^u]" and see whether there are True values.

### (4)
Considering the tendency of British English one can use regex "ou|ae|oe|ise$|yse$"

### (5)
"^(010|02)-\\d\\d\\d\\d-\\d\\d\\d\\d"

## (c)
### (1)
"a?" is equivalent to "a{0,1}".
"a+" is equivalent to "a{1,}".
"a*" is equivalent to "a{0,}".

### (2)
```{r}
#^.*$ matches any string except a new line.
#"\\{.+\\}" matches at least one character inside curly brackets.
#\d{4}-\d{2}-\d{2} matches 4 digitits folowed by - followed by 2 digits followed
#by - followed by 2 digits.
#"\\\\{4}" matches 4 \.
```

## (d)
### (1)
```{r}
str_subset(words, "^x|x$")
```
```{r}
str_subset(words, "^[aeiou].*[^aeiou]") %>% 
    head()
```
```{r}
words[str_detect(words, "a")&
      str_detect(words, "e")&
      str_detect(words, "i")&
      str_detect(words, "o")&
      str_detect(words, "u")]
```

### (2)
```{r}
max_num=max(str_count(words, "[aeiou]"))
words[(str_count(words, "[aeiou]"))==max_num]
```
```{r}
prop=str_count(words, "[aeiou]")/str_length(words)
words[prop==max(prop)]
```

# 3
## (1)
```{r}
library(gutenbergr)
gutenberg_metadata %>% 
    filter(str_detect(title, 
                      "^Pride and Prejudice$")) %>% 
    select(gutenberg_id)
```

## (2)
```{r}
gutenberg_works(languages="en") %>%
    filter(str_detect(title, 
                      "^Pride and Prejudice$")) %>% 
    select(gutenberg_id)
```

## (3)
```{r}
book=gutenberg_download(1342)
```

## (4)
```{r}
library(tidytext)
words=book %>% unnest_tokens(word, text)
head(words)
```

## (5)
```{r}
words=words %>% 
    mutate(word_num=1:length(word))
head(words)
```

## (6)
```{r}
words=words %>% anti_join(stop_words) %>% 
    filter(!str_detect(word, "^\\d+$"))
head(words)
```

## (7)
```{r}
sentiment=get_sentiments("afinn")
words=words %>% inner_join(sentiment, by="word")
head(words)
```

## (8)
```{r}
words %>% ggplot(aes(x=word_num, y=value))+
    geom_point(size=.3, alpha=.5)+
    geom_smooth()
```




