---
title: |
  | \LARGE HW2
author: |
  | \large \rm 2019150432 임효진
date: |
  | \rm \today
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
mainfont: NanumBarunGothic
fontsize: 11pt
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

# 1
## (a)
$\int_{\infty}^{\infty}\int_{\infty}^{\infty}cI(x^2+y^2\leq1)dydx\\=\int_{-1}^{1}\int_{-\sqrt{1-x^2}}^{\sqrt{1-x^2}}cdydx\\=4c\int_{0}^{1}\sqrt{1-x^2}dx\\=4c\int_{0}^{\pi/2}\sqrt{1-\sin^2\theta}\cos\theta d\theta\\=\pi c\\=1$

Thus $c=1/\pi$.

```{r}
n=10^4
x=runif(n ,min=-1,max=1)
y=runif(n ,min=-1,max=1)
circle=x^2 + y^2 <= 1^2
pi=(sum(circle)/n)*4

c=1/pi
c
```

## (b)
```{r}
n=10^4
u1=runif(n, -1, 1)
u2=runif(n, -1, 1)
x=u1[u1^2+u2^2<1]
y=u2[u1^2+u2^2<1]
hist(x, nclass=40, freq=F)
curve((2/pi)*sqrt(1-x^2), -1,1, add=TRUE)

hist(y, nclass=40, freq=F)
curve((2/pi)*sqrt(1-x^2), -1,1, add=TRUE)
```

## (c)
```{r}
n=10^4

simBeta=function(a, b){
  u1=runif(a)
  u2=runif(b)
  R=sum(log(u1))/(sum(log(u1))+log(u2))
}

randR=replicate(n, simBeta(2, 1))
hist(randR, nclass=30, freq = F)
curve(dbeta(x, 2, 1), 0, add=T)
```


# 2
## (a)
### 4.4
```{r}
simHit=function(){
  perm=sample(1:100, 100, replace = F)
  return(sum(perm==seq(100)))
}

randHit=replicate(1000, simHit())
mean(randHit)
var(randHit)
```
The exact value of the expectation and the variance should be 1. The simulation derives a value close to 1 for both statistics.

### 4.7
```{r}
simDice=function(){
  a=array()
  while(length(unique(a))<12){
    temp=sum(sample(1:6, size = 2, replace = TRUE))
    a=c(a, temp)
  }
  return(length(a)-1)
}

randDice=replicate(1000, simDice())
mean(randDice)
```

### 4.13
```{r}
lambda=5 
n=10^4

# inverse transform method
simP1=function(lambda) {
  X=0
  px=exp(-lambda)
  Fx=px
  U=runif(1)
  while (Fx < U) {
    X=X + 1
    px=px*lambda/X
    Fx=Fx + px
  }
  return(X)
}
poissonX1=replicate(n,simP1(lambda))
hist(poissonX1, freq = F)
mean(poissonX1<=3)

# truncated distribition
simP2=function(lambda){
  x=rexp(100, lambda)
  u=runif(100, 0, 1)
  if(x[1]>1) {return(0)}
  else {return(max(which(cumsum(x)<1)))}
}
poissonX2=replicate(n, simP2(lambda))
hist(poissonX2, freq=F)
mean(poissonX2<=3)

ppois(3, lambda)
```

## (b)
### 5.1
```{r}
n=10^4
u=runif(n)
X=log(1+u*(exp(1)-1))

mean(X)
var(X)

hist(X, freq = F)
```

### 5.9
```{r}
n=10^4
u1=runif(n)
u2=runif(n)
Y=-log(u1)
X=u2^(1/Y)

mean(X)
var(X)

hist(X, freq=F)
```

### 5.19
```{r}
# inverse transform method
n=10^4
u=runif(n)
X=(-1+sqrt(1+8*u))/2

mean(X)
var(X)

hist(X, freq=F)

# rejection method
simRej=function(fx, a, b, M){
  while(T){
    y=runif(1, a, b)
    u=runif(1)
    if(M*u/(b-a) < fx(y)) return(y)
  }
}
fx=function(x) {1/2+x}
randRej=replicate(n, simRej(fx, 0, 1, 3/2))

mean(randRej)
var(randRej)

hist(randRej, freq=F)

# composition method
u1=runif(n)
u2=runif(n)
X=u2*(u1<1/2)+sqrt(u2)*(u1>=1/2)

mean(X)
var(X)

hist(X, freq=F)
```
